upstream fastapi_pool {
    server web:8000;
    server web-1:8000;
    server web-2:8000;
}

server {
    listen 80;

    location / {
        proxy_pass http://fastapi_pool;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location /health/live {
        proxy_pass http://fastapi_pool/health/live;
    }
}
